name: bomber_app2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/data/questions_g1.json
    - assets/data/questions_g2.json
    - assets/data/questions_g3.json
    - assets/data/questions_g4.json
    - assets/data/questions_g5.json
    - assets/data/questions_g6.json
    - assets/data/questions_g7.json
    - assets/data/questions_g8.json
    - assets/data/questions_g9.json
    - assets/data/questions_g10.json
    - assets/data/questions_g11.json
    - assets/data/questions_e3.json
    - assets/data/questions_e4.json
    - assets/data/questions_e5.json
    - assets/data/questions_e6.json
    - assets/data/questions_e7.json
    - assets/data/questions_s1.json
